-------------------------------------------------------------------------------
Test set: pe.edu.pucp.softinv.dao.PublicacionDAOTest
-------------------------------------------------------------------------------
Tests run: 5, Failures: 1, Errors: 4, Skipped: 0, Time elapsed: 8.374 s <<< FAILURE! -- in pe.edu.pucp.softinv.dao.PublicacionDAOTest
pe.edu.pucp.softinv.dao.PublicacionDAOTest.testInsertar -- Time elapsed: 3.788 s <<< ERROR!
java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`mydb`.`PUBLICACION`, CONSTRAINT `fk_Publicación_MATERIAL1` FOREIGN KEY (`MATERIAL_MATERIAL_ID`) REFERENCES `MATERIAL` (`MATERIAL_ID`))
	at pe.edu.pucp.softinv.daoImpl.PublicacionDAOImpl.insertar(PublicacionDAOImpl.java:29)
	at pe.edu.pucp.softinv.dao.PublicacionDAOTest.testInsertar(PublicacionDAOTest.java:78)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`mydb`.`PUBLICACION`, CONSTRAINT `fk_Publicación_MATERIAL1` FOREIGN KEY (`MATERIAL_MATERIAL_ID`) REFERENCES `MATERIAL` (`MATERIAL_ID`))
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:938)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1106)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1045)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1369)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1030)
	at pe.edu.pucp.softinv.daoImpl.PublicacionDAOImpl.insertar(PublicacionDAOImpl.java:24)
	... 4 more

pe.edu.pucp.softinv.dao.PublicacionDAOTest.testObtenerPorId -- Time elapsed: 1.124 s <<< ERROR!
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "id" is null
	at pe.edu.pucp.softinv.daoImpl.PublicacionDAOImpl.obtenerPorId(PublicacionDAOImpl.java:42)
	at pe.edu.pucp.softinv.dao.PublicacionDAOTest.testObtenerPorId(PublicacionDAOTest.java:85)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "id" is null
	at pe.edu.pucp.softinv.daoImpl.PublicacionDAOImpl.obtenerPorId(PublicacionDAOImpl.java:37)
	... 4 more

pe.edu.pucp.softinv.dao.PublicacionDAOTest.testModificar -- Time elapsed: 1.110 s <<< ERROR!
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "id" is null
	at pe.edu.pucp.softinv.daoImpl.PublicacionDAOImpl.obtenerPorId(PublicacionDAOImpl.java:42)
	at pe.edu.pucp.softinv.dao.PublicacionDAOTest.testModificar(PublicacionDAOTest.java:92)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "id" is null
	at pe.edu.pucp.softinv.daoImpl.PublicacionDAOImpl.obtenerPorId(PublicacionDAOImpl.java:37)
	... 4 more

pe.edu.pucp.softinv.dao.PublicacionDAOTest.testListarTodos -- Time elapsed: 1.218 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:183)
	at pe.edu.pucp.softinv.dao.PublicacionDAOTest.testListarTodos(PublicacionDAOTest.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)

pe.edu.pucp.softinv.dao.PublicacionDAOTest.testEliminar -- Time elapsed: 1.124 s <<< ERROR!
java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "pe.edu.pucp.softinv.model.PublicacionDTO.getPublicacionId()" is null
	at pe.edu.pucp.softinv.daoImpl.PublicacionDAOImpl.eliminar(PublicacionDAOImpl.java:80)
	at pe.edu.pucp.softinv.dao.PublicacionDAOTest.testEliminar(PublicacionDAOTest.java:110)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "pe.edu.pucp.softinv.model.PublicacionDTO.getPublicacionId()" is null
	at pe.edu.pucp.softinv.daoImpl.PublicacionDAOImpl.eliminar(PublicacionDAOImpl.java:78)
	... 4 more

